{{- if .Values.realm.import.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  miravelo-realm.yaml: |
{{ .Files.Get "files/miravelo-realm.yaml" | indent 4 }}
{{- end }}
