apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop-frontend.fullname" . }}-config
  labels:
    {{- include "shop-frontend.labels" . | nindent 4 }}
data:
  app.env: |
    KEYCLOAK_URL={{ required "shop-frontend: env.KEYCLOAK_URL is required" .Values.env.KEYCLOAK_URL }}
    KEYCLOAK_REALM={{ required "shop-frontend: env.KEYCLOAK_REALM is required" .Values.env.KEYCLOAK_REALM }}
    KEYCLOAK_CLIENT_ID={{ required "shop-frontend: env.KEYCLOAK_CLIENT_ID is required" .Values.env.KEYCLOAK_CLIENT_ID }}
