image:
  pullPolicy: Never

ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

env:
  KEYCLOAK_URL: "http://localhost:8080/auth"
  KEYCLOAK_REALM: "retail"
  KEYCLOAK_CLIENT_ID: "shop-frontend"
